import type { CSSProperties } from "react";
import { motionTokens } from "../features/player/motionTokens";

export const motion = {
  focusInMs: 680,
  revealMs: 420,
  buttonMs: 160,
  qrPanelMs: 320,
  journeyTotalMs: 1_650,
  journeyReducedTotalMs: 280,
  qrMergeMs: 620,
  ringExpandMs: 860,
  ambientShiftMs: 420,
  libraryRevealMs: 520,
  detailTransitionMs: 520,
  detailReducedTransitionMs: 140,
  detailCopyDelayMs: 250,
  trackStaggerMs: 14,
  wallPanelMs: 420,
  wallTileHoverMs: 260,
  wallTileReturnMs: 560,
  wallClickDelayMs: 190,
  wallDriftPxPerSecond: 11,
  wallWheelStrength: 0.72,
  wallAutoResumeMs: 2_800,
  wallTiltMaxDeg: 5,
  wallHoverDepthPx: 32,
  wallHoverScale: 1.065,
  particleResponseDamping: 0.075,
  particleBeatDecay: 0.86,
  playerEnterMs: motionTokens.spaceTransitionDuration,
  playerEnterReducedMs: motionTokens.coverPassage.reducedDuration,
  playerExitMs: motionTokens.playerExitDuration,
  playerExitReducedMs: motionTokens.playerExitReducedDuration,
  playerLockMs: motionTokens.coverPassage.sharpApproachStart,
  playerDetachMs: motionTokens.coverPassage.sharpApproachEnd,
  playerTraverseMs: motionTokens.coverPassage.listeningSpaceStart,
  playerLyricDelayMs: motionTokens.coverPassage.listeningSpaceStart,
  playerLyricFocusMs: 400,
  playerAudioFadeDelayMs: 980,
  playerAudioFadeMs: 720,
  playerControlsHideMs: 3_000,
  playerControlsRevealMs: 180,
  listeningSpaceExitMs: motionTokens.listeningSpaceSwitch.exitMs,
  listeningSpaceEnterMs: motionTokens.listeningSpaceSwitch.enterMs,
  flowShiftMs: 680,
  flowOpacityMs: 380,
  flowBlurMs: 460,
  flowTypeMs: motionTokens.lyricRevealDuration,
  scrollLyricFocusMs: 460,
  scrollLyricFlowPxPerSecond: 30,
  scrollLyricPastDriftMs: 5_200,
  scrollLyricFutureApproachMs: 4_800,
  scrollLyricOriginLineCount: 2,
  scrollLyricContinuityGapMs: 1_200,
  scrollLyricInterludeGapMs: 3_500,
  scrollLyricReturnMs: 520,
  scrollLyricInterludeSpeed: 0.34,
  scrollLyricInterludeRampMs: 540,
  scrollLyricEndingHoldMs: 760,
  scrollLyricEndingFadeMs: 1_480,
  scrollLyricGapTraceOffsetRatio: 0.14,
  scrollLyricGapPreviewOffsetRatio: 0.18,
  ambientCycleMinMs: motionTokens.fogCycleMinMs,
  ambientCycleMaxMs: motionTokens.fogCycleMaxMs,
  reducedMs: 80,
  easing: {
    gentle: "cubic-bezier(0.22, 1, 0.36, 1)",
    quiet: "cubic-bezier(0.4, 0, 0.2, 1)",
    snap: "cubic-bezier(0.16, 1, 0.3, 1)",
  },
} as const;

type MotionVariables = CSSProperties & Record<`--motion-${string}`, string>;

export const motionCssVariables: MotionVariables = {
  "--motion-focus-in": `${motion.focusInMs}ms`,
  "--motion-reveal": `${motion.revealMs}ms`,
  "--motion-button": `${motion.buttonMs}ms`,
  "--motion-panel": `${motion.qrPanelMs}ms`,
  "--motion-journey": `${motion.journeyTotalMs}ms`,
  "--motion-qr-merge": `${motion.qrMergeMs}ms`,
  "--motion-ring-expand": `${motion.ringExpandMs}ms`,
  "--motion-ambient-shift": `${motion.ambientShiftMs}ms`,
  "--motion-library-reveal": `${motion.libraryRevealMs}ms`,
  "--motion-detail": `${motion.detailTransitionMs}ms`,
  "--motion-detail-reduced": `${motion.detailReducedTransitionMs}ms`,
  "--motion-detail-copy-delay": `${motion.detailCopyDelayMs}ms`,
  "--motion-track-stagger": `${motion.trackStaggerMs}ms`,
  "--motion-wall-panel": `${motion.wallPanelMs}ms`,
  "--motion-wall-tile": `${motion.wallTileHoverMs}ms`,
  "--motion-wall-return": `${motion.wallTileReturnMs}ms`,
  "--motion-player-enter": `${motion.playerEnterMs}ms`,
  "--motion-player-enter-reduced": `${motion.playerEnterReducedMs}ms`,
  "--motion-player-exit": `${motion.playerExitMs}ms`,
  "--motion-player-exit-reduced": `${motion.playerExitReducedMs}ms`,
  "--motion-player-lock": `${motion.playerLockMs}ms`,
  "--motion-player-detach": `${motion.playerDetachMs}ms`,
  "--motion-player-traverse": `${motion.playerTraverseMs}ms`,
  "--motion-player-lyric-delay": `${motion.playerLyricDelayMs}ms`,
  "--motion-player-lyric-focus": `${motion.playerLyricFocusMs}ms`,
  "--motion-player-controls": `${motion.playerControlsRevealMs}ms`,
  "--motion-space-exit": `${motion.listeningSpaceExitMs}ms`,
  "--motion-space-enter": `${motion.listeningSpaceEnterMs}ms`,
  "--motion-flow-shift": `${motion.flowShiftMs}ms`,
  "--motion-flow-opacity": `${motion.flowOpacityMs}ms`,
  "--motion-flow-blur": `${motion.flowBlurMs}ms`,
  "--motion-flow-type": `${motion.flowTypeMs}ms`,
  "--motion-scroll-focus": `${motion.scrollLyricFocusMs}ms`,
  "--motion-reduced": `${motion.reducedMs}ms`,
  "--motion-gentle": motion.easing.gentle,
  "--motion-quiet": motion.easing.quiet,
  "--motion-snap": motion.easing.snap,
};
